apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: cicd-dem
    app.kubernetes.io/instance: cicd-dem-instance
    app.kubernetes.io/version: '1.0.0'
    app.kubernetes.io/managed-by: kubectl
  name: cicd-dem-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-dem
  template:
    metadata:
      labels:
        app: cicd-dem
    spec:
      containers:
        - image: 445613004598.dkr.ecr.ap-south-1.amazonaws.com/cicd-dem:latest
          imagePullPolicy: Always
          name: cicd-dem
          ports:
            - containerPort: 3000
